### PR TITLE
Some escaping needed.

### PR DESCRIPTION
**Pull request by agafonovdmitry**

### CODE REVIEW

**Comment by matteocontrini** [comment]
Thanks. But are you sure this is needed? An XML file with symbols like `<` within a node wouldn't even be valid. And I hope the Microsoft's Windows Phone app isn't generating invalid XML files

**Comment by agafonovdmitry** [comment]
Not sure about other characters, but I've got double quotes inside attributes after conversion.
I think this is the XML library decode chars here:
`text = m.find('Body').text`
and we need to encode them back as we write out XML manually.

**Comment by matteocontrini** [comment]
Ok, I've checked and concluded that:
1) encoding `<`, `>` and `&` is not necessary because those entities should already be encoded in the .msg file (by MS). Correct me if this seems wrong to you
2) encoding `"` is actually needed! I don't even know how the script has worked for everyone without escaping quotes...

Also note that the order of the `replace`s that you're doing can create problems, because you're first replacing `<` to `&lt;` and then `&` to `&amp;`, possibly creating weird things like `&amp;lt;`.
If it looks good to you, I'd say to keep only the part that escapes the quotes.

**Comment by agafonovdmitry** [comment]
Hm, okay :)
Changed.

**Pull request merged**
