### PR TITLE
Add support for converting MMS messages

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by sebastian-frysztak** [comment]
it works fine, however for Python 3 it throws this:

```
Total count of messages: 41

[====                ] processing 10Traceback (most recent call last):
  File "convert.py", line 125, in <module>
    base64_string = attachment.find('AttachmentDataBase64String').text.decode('base64')
AttributeError: 'str' object has no attribute 'decode'
```

**Comment by sschuberth** [comment]
@sebastian-frysztak Thanks for the report, this should be fixed now. Mind trying it again?

**Comment by sschuberth** [comment]
So, while it's working fine for me I'd still prefer to have at least one other user confirm.

**Comment by sebastian-frysztak** [comment]
I'm sorry, I forgot about this.
I can confirm that updated version works fine under Python 3.

**Comment by sschuberth** [comment]
Thanks for reporting back, @sebastian-frysztak!

**Comment by matteocontrini** [comment]
Thank you everyone! :)

**Pull request merged**
